In [1]:
import torch
from torch import nn

In [2]:
# neuron
def neuron(input_data):
    
    W = torch.tensor([0.5,0.5,0.5])
    b = torch.tensor([0.5])
    
    return torch.matmul(input_data, W) + b

In [3]:
neuron(torch.tensor([1,2,3], dtype=torch.float32))

tensor([3.5000])

In [4]:
nn.ReLU()

ReLU()

In [5]:
# NN
def fnn(input):
    model = nn.Sequential(
        nn.Linear(10,128),
        nn.ReLU(),
        nn.Linear(128,64),
        nn.ReLU(),
        nn.Linear(64,2)
    )

    return model(input)

In [6]:
res = fnn(torch.tensor([0.2000, 0.4000, 0.2000, 0.4000, 0.2000, 0.4000, 0.2000, 0.4000, 0.2000, 0.4000]))
res

tensor([-0.0096,  0.1536], grad_fn=<AddBackward0>)

## Exercise activation functions

In [40]:
import torch

seed = 172
torch.manual_seed(seed)


def m_sigmoid(x):
    return 1 / (1 + torch.exp(-x))

def m_tanh(x):
    return (torch.exp(x) - torch.exp(-x)) / (torch.exp(x) + torch.exp(-x))


def m_relu(x):
    return torch.max(test,torch.tensor(0)) # or torch.mul(x, (x>0))


def m_softmax(x):
    return torch.exp(x)/ torch.sum(torch.exp(x))

In [41]:
test = torch.tensor([0.2000, 0.6000, -0.2000, 0.4000, 0.2000, 0.4000, 0.2000, 0.4000, 0.2000, 0.4000])

In [42]:
m_sigmoid(test)

tensor([0.5498, 0.6457, 0.4502, 0.5987, 0.5498, 0.5987, 0.5498, 0.5987, 0.5498,
        0.5987])

In [43]:
m_tanh(test)

tensor([ 0.1974,  0.5370, -0.1974,  0.3799,  0.1974,  0.3799,  0.1974,  0.3799,
         0.1974,  0.3799])

In [44]:
m_relu(test)

tensor([0.2000, 0.6000, 0.0000, 0.4000, 0.2000, 0.4000, 0.2000, 0.4000, 0.2000,
        0.4000])

In [45]:
m_softmax(test)

tensor([0.0905, 0.1350, 0.0607, 0.1106, 0.0905, 0.1106, 0.0905, 0.1106, 0.0905,
        0.1106])