In [1]:
import torch

In [2]:
def conv2d(image, kernel):
    output = torch.zeros(len(image) - len(kernel) + 1,len(image[0]) - len(kernel[0]) + 1)
    for i in range(len(output)):
        for j in range(len(output[0])):
            output[i][j] = torch.sum(image[i:i+len(kernel),j:j+len(kernel[0])] * kernel)
            
    return output

In [3]:
image = torch.ones(12,3)

In [4]:
image

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [5]:
kernel = torch.randn(3,3)

In [6]:
kernel

tensor([[ 0.4677,  2.5862,  0.8537],
        [-0.0865, -0.3084, -0.1110],
        [-0.3407,  0.1447, -0.2953]])

In [7]:
output = torch.zeros(len(image) - len(kernel) + 1,len(image[0]) - len(kernel[0]) + 1)

In [8]:
output

tensor([[0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.]])

In [9]:
conv2d(image,kernel)

tensor([[2.9103],
        [2.9103],
        [2.9103],
        [2.9103],
        [2.9103],
        [2.9103],
        [2.9103],
        [2.9103],
        [2.9103],
        [2.9103]])

In [10]:
kernel

tensor([[ 0.4677,  2.5862,  0.8537],
        [-0.0865, -0.3084, -0.1110],
        [-0.3407,  0.1447, -0.2953]])

In [11]:
image[0:3,0:3]

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [12]:
# solution better
def conv2d(image, kernel):
    output = torch.zeros(len(image) - len(kernel) + 1,len(image[0]) - len(kernel[0]) + 1)
    for i in range(len(output)):
        for j in range(len(output[0])):
            output[i,j] = torch.sum(image[i:i+len(kernel),j:j+len(kernel[0])] * kernel)
            
    return output